FROM public.ecr.aws/gridx/base-images:golang-dev-1.17.latest

ARG HOST_OS
ARG HOST_ARCH
ARG SRC_BIN=bin/gxctl-${HOST_OS}-${HOST_ARCH}

COPY ${SRC_BIN} /usr/bin/gxctl
RUN chmod +x /usr/bin/gxctl
RUN mkdir -p /root/.gxctl && \
  touch /root/.gxctl/config.yaml && \
  /usr/bin/gxctl ssh setup > /tmp/ssh_config && \
  sed -e s~"gxctl ssh tunnel --profile"~"gxctl ssh tunnel --skip-config-check -q --profile"~g /tmp/ssh_config >> /etc/ssh/ssh_config && \
  rm /root/.gxctl/config.yaml
