steps:
- label: ":bash: Shellcheck"
  plugins:
  - shellcheck#v1.1.2:
      files:
      - "bin/*.sh"
- command:
  - "make ci_test"
  label: ":golang: Test"
  agents:
  - "queue=default"
- command:
  - "make ci_build"
  label: ":golang: Build"
  agents:
  - "queue=default"
  artifact_paths:
  - "bin/*"
- wait
- command:
  - "buildkite-agent artifact download \"bin/gxctl-*\" . --step \":golang: Build\""
  - "make docker"
  - ".buildkite/steps/aws_ecr_auth.sh"
  - "make docker_push"
  label: ":docker: Build docker image"
  agents:
  - "queue=default"
- command:
  - "make ci_release"
  label: ":golang: Release"
  artifact_paths:
  - "dist/*"
  if: "build.tag != null"
