steps:
- command:
  - "make ci_build"
  label: ":golang: Build"
  agents:
  - "queue=default"
  artifact_paths:
  - "bin/*"
- wait
- command:
  - "buildkite-agent artifact download bin/* . --step \":golang: Build\""
  - "make docker"
  label: ":docker: Build docker image"
  agents:
  - "queue=default"
  branches: "!master"
- command:
  - "buildkite-agent artifact download bin/* . --step \":golang: Build\""
  - "make docker"
  - ".buildkite/steps/aws_ecr_auth.sh"
  - ".buildkite/steps/push.sh && echo 'Nothing to do' || make docker_push"
  label: ":docker: Push docker image"
  agents:
  - "queue=default"
  branches: "master"