apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gxctl
  description: Command-line interface to the DS management API
  annotations:
    github.com/project-slug: grid-x/gxctl
    buildkite.com/project-slug: gridX/gxctl
spec:
  type: service
  lifecycle: production
  owner: sre-device-infrastructure-team
  system: device-services
  consumesApis:
  - ds-management-api
